from pathlib import Path

source=Path('index-v2.html').read_text(encoding='utf-8')
source=source.replace("const theme='neon';","let theme='neon';")
source=source.replace('</style>',Path('unified.css').read_text(encoding='utf-8')+'\n</style>',1)
source=source.replace("let activeMode='home'",Path('unified.js').read_text(encoding='utf-8')+"\nlet activeMode='home'",1)
source=source.replace('</header><main','</header><div id="theme-controls"></div><main',1)
source=source.replace('<a id="other" href="talao-v2.html"></a>','<button id="other" data-action="modes"></button>')
source=source.replace("function render(){", "function render(){\n $('#theme-controls').innerHTML=themeBar();")
source=source.replace(" $('#app').innerHTML=html;", " if(screen==='wheel')html=wheelView();\n $('#app').innerHTML=html;")
source=source.replace("function go(next){clearClock();", "function go(next){if(next!=='wheel')clearWheel();clearClock();")
source=source.replace("buzz();if(extraAction(action,v))", "buzz();if(unifiedAction(action,v))return;if(extraAction(action,v))")
source=source.replace("$('#other').textContent=theme==='neon'?t('Ver talão ↗','View receipt ↗'):t('Ver néon ↗','View neon ↗');", "$('#other').textContent=t('Todos os modos ↗','All modes ↗');")
source=source.replace('<div class="mode-menu">', '''<button class="btn game-link wheel-cta" data-action="wheel-open"><span>↻ ${t('Roda da sorte','Wheel of fortune')}<small>${t('Tu rodas. A sorte escolhe.','You spin. Chance chooses.')}</small></span><span class="arrow">✳</span></button><div class="mode-menu">''')
source=source.replace("${privacy()}`}\nfunction modeArt", "${btn('Ou rodar a sorte ↻','Or spin the wheel ↻','wheel-open','','secondary small')}${privacy()}`}\nfunction modeArt")
source=source.replace('<title>Luxder v2 — Quatro maneiras de meter conversa</title>','<title>Luxder — Todos os jogos, uma app</title>')
source=source.replace("t('edição da noite','night edition')", "t('todos os jogos','all the games')")
source=source.replace('</style>',Path('grill-taps.css').read_text(encoding='utf-8')+'\n</style>',1)
source=source.replace('render();\n</script>',Path('grill-taps.js').read_text(encoding='utf-8')+'\nrender();\n</script>')
source=source.replace("function unifiedAction(action,value){", "function unifiedAction(action,value){if(action==='grill-tap'){grillTap(value);return true}if(action==='grill-ready'){go('grill-guess');return true}")
source=source.replace(" if(screen==='wheel')html=wheelView();", " if(screen==='wheel')html=wheelView();\n if(screen==='grill-handoff')html=grillHandoff();")
source=source.replace('2 · adivinha, confirma, pergunta mais','2 · cinco perguntas, sempre duas opções').replace('2 · guess, confirm, ask a little more','2 · five questions, always two choices')
Path('luxder.html').write_text(source,encoding='utf-8')
print('Built luxder.html: all modes + live theme toggles + fortune wheel.')
