// Every pair is authored in Portuguese and English. No remote content or AI calls.
const convincePrompts = [
['Os patos deviam controlar o trânsito.','Ducks should control traffic.'],
['Um pastel de nata é uma unidade de tempo.','A custard tart is a unit of time.'],
['A melhor declaração de amor é emprestar um carregador.','The best declaration of love is lending someone a charger.'],
['Os elevadores precisam de DJ residente.','Lifts need a resident DJ.'],
['Uma bicicleta sem rodas é um ginásio emocional.','A bicycle without wheels is an emotional gym.'],
['O teu cotovelo merece um documentário.','Your elbow deserves a documentary.'],
['Os pombos são drones com contrato sem termo.','Pigeons are drones with permanent contracts.'],
['A fila do bar devia dar créditos universitários.','The bar queue should earn university credits.'],
['Um date no supermercado devia ter passadeira vermelha.','A supermarket date deserves a red carpet.'],
['As meias desaparecidas fundaram uma civilização.','Missing socks founded a civilisation.'],
['O techno é uma máquina de lavar com ambição.','Techno is a washing machine with ambition.'],
['A lua devia pagar condomínio.','The moon should pay building maintenance fees.'],
['O despertador devia pedir consentimento.','Alarm clocks should ask for consent.'],
['A sopa é um smoothie com um cargo importante.','Soup is a smoothie with an important job.'],
['O silêncio constrangedor merece um aplauso.','Awkward silence deserves applause.'],
['Todos os táxis deviam ter um botão de confettis.','Every taxi should have a confetti button.'],
['Uma torradeira pode ser uma excelente conselheira amorosa.','A toaster can be an excellent love adviser.'],
['Os semáforos são festas com uma péssima seleção musical.','Traffic lights are parties with terrible music.'],
['Devia haver férias para recuperar de férias.','We need holidays to recover from holidays.'],
['A sesta devia ser modalidade olímpica.','Napping should be an Olympic sport.'],
['O primeiro encontro ideal inclui observar uma rotunda.','The ideal first date includes watching a roundabout.'],
['O bengaleiro sabe demais e precisa de proteção de testemunhas.','The cloakroom knows too much and needs witness protection.'],
['Um guardanapo dobrado é arquitetura.','A folded napkin is architecture.'],
['O arroz doce devia ter direito de voto.','Rice pudding should have voting rights.'],
['A tua dança precisa de legendas.','Your dancing needs subtitles.'],
['As plantas fazem gossip quando saímos de casa.','Plants gossip when we leave the house.'],
['Uma sardinha seria uma ótima ministra do mar.','A sardine would make an excellent minister of the sea.'],
['Um abraço devia vir com instruções de montagem.','A hug should come with assembly instructions.'],
['A melhor app de dating é a meteorologia.','The best dating app is the weather forecast.'],
['Os caracóis chegam atrasados por princípio.','Snails are late on principle.'],
['Uma discoteca às 6h devia servir pequeno-almoço na pista.','At 6 am, clubs should serve breakfast on the dance floor.'],
['O pão de alho é uma linguagem do amor.','Garlic bread is a love language.'],
['O sinal de Wi-Fi devia aparecer nas árvores.','Wi-Fi bars should grow on trees.'],
['Os chinelos são sapatos em teletrabalho.','Slippers are shoes working from home.'],
['Uma gaivota roubou-te o plano de negócios.','A seagull stole your business plan.'],
['O DJ devia aceitar pedidos por pombo-correio.','DJs should accept requests by carrier pigeon.'],
['Uma conversa sobre batatas pode salvar um date.','A conversation about potatoes can save a date.'],
['O gelo está a fazer uma greve silenciosa no teu copo.','The ice in your glass is on a silent strike.'],
['Os gatos inventaram as reuniões que podiam ser emails.','Cats invented meetings that could have been emails.'],
['Todas as desculpas deviam rimar.','Every apology should rhyme.'],
['Uma bola de espelhos é um sol com vida social.','A disco ball is a sun with a social life.'],
['A pessoa que desenha rotundas é secretamente um coreógrafo.','The person designing roundabouts is secretly a choreographer.'],
['O metro fechado é um escape room demasiado convincente.','A closed metro is an overly convincing escape room.'],
['Os guarda-chuvas deviam ter nomes de artistas.','Umbrellas should have stage names.'],
['Uma salada russa precisa de passaporte.','A Russian salad needs a passport.'],
['A tua playlist é um currículo emocional.','Your playlist is an emotional CV.'],
['As escadas rolantes são passadeiras de moda gratuitas.','Escalators are free fashion runways.'],
['Um polvo resolveria a fila do bar.','An octopus would solve the bar queue.'],
['O meu casaco tem mais planos para esta noite do que eu.','My jacket has more plans for tonight than I do.'],
['Devia haver um prémio para a melhor saída discreta.','There should be an award for the best discreet exit.'],
['O brunch é um pequeno-almoço que perdeu o autocarro.','Brunch is breakfast that missed the bus.'],
['As nuvens estão só a experimentar penteados.','Clouds are just trying out hairstyles.'],
['A melhor viagem de casal é até à máquina de snacks.','The best couples trip is to the snack machine.'],
['Um pato de borracha pode ser capitão de um cruzeiro.','A rubber duck can captain a cruise ship.'],
['O botão de soneca é o verdadeiro chefe de família.','The snooze button is the real head of the household.'],
['Os espelhos deviam dar conselhos sobre horários.','Mirrors should give scheduling advice.'],
['Um bom date merece comentários de futebol.','A good date deserves football commentary.'],
['O bacalhau tem demasiados disfarces para ser inocente.','Cod has too many disguises to be innocent.'],
['O micro-ondas devia anunciar os pratos como um maître.','Microwaves should announce dishes like a maître d’.'],
['Uma bicicleta ciumenta faz mais barulho nas curvas.','A jealous bicycle squeaks louder on corners.'],
['As filas deviam ter intervalos publicitários.','Queues should have advertising breaks.'],
['Uma almofada devia poder pedir um dia de folga.','A pillow should be allowed to request a day off.'],
['O melhor elogio é «confio-te a minha última batata frita».','The best compliment is “I trust you with my last chip”.'],
['O teu frigorífico está a ensaiar para uma banda.','Your fridge is rehearsing for a band.'],
['Um autocarro vazio devia ser uma discoteca móvel.','An empty bus should become a mobile disco.'],
['Todas as cartas de amor precisam de um mapa.','Every love letter needs a map.'],
['Os cogumelos parecem guarda-chuvas de uma aldeia organizada.','Mushrooms look like umbrellas in a well-organised village.'],
['A palavra «obviamente» devia resolver discussões de trânsito.','The word “obviously” should settle traffic disputes.'],
['Uma esponja tem o melhor currículo de limpeza emocional.','A sponge has the best emotional-cleaning CV.'],
['O amor à primeira vista precisa de óculos de leitura.','Love at first sight needs reading glasses.'],
['As gaivotas deviam pagar pelos concertos que interrompem.','Seagulls should pay for the concerts they interrupt.'],
['Uma pizza quadrada é uma tese contra o sistema.','A square pizza is a thesis against the system.'],
['O romantismo atingiu o auge com a extensão elétrica.','Romance peaked with the extension lead.'],
['Uma estátua deve receber comissão pelas selfies.','Statues should earn commission on selfies.'],
['O teu nome de DJ devia ser um erro de autocorretor.','Your DJ name should be an autocorrect mistake.'],
['As batatas fritas são talheres com autoestima.','Chips are cutlery with self-esteem.'],
['O beijo de boa noite devia ser substituível por um high-five épico.','A goodnight kiss should be replaceable with an epic high-five.'],
['Uma biblioteca de discoteca emprestaria desculpas.','A nightclub library would lend excuses.'],
['Os bancos de jardim são terapeutas a tempo inteiro.','Park benches are full-time therapists.'],
['Uma bússola precisa de terapia quando se apaixona.','A compass needs therapy when it falls in love.'],
['Os carrosséis são aulas de condução para sonhadores.','Carousels are driving lessons for dreamers.'],
['A última azeitona deve ser decidida por debate parlamentar.','The last olive should be decided by parliamentary debate.'],
['Um date com um fantasma teria menos ghosting.','Dating a ghost would involve less ghosting.'],
['As bicicletas deviam buzinar elogios.','Bicycle bells should ring out compliments.'],
['O chão da pista merece férias nas Caraíbas.','The dance floor deserves a Caribbean holiday.'],
['Uma mala de viagem tem mais histórias do que um podcast.','A suitcase has more stories than a podcast.'],
['Os pepinos são courgettes que escolheram outra carreira.','Cucumbers are courgettes that chose a different career.'],
['O Cupido devia trocar o arco por uma máquina de senhas.','Cupid should swap the bow for a ticket machine.'],
['Um casal que monta uma tenda merece um diploma.','A couple who assemble a tent deserve a diploma.'],
['Os pinguins já vêm vestidos para o melhor date.','Penguins are already dressed for the perfect date.'],
['Uma máquina de café podia presidir ao Parlamento.','A coffee machine could chair Parliament.'],
['O vento é um cabeleireiro sem licença.','Wind is an unlicensed hairdresser.'],
['Uma discussão sobre ananás na pizza devia acabar em dança.','A pineapple-on-pizza argument should end in a dance.'],
['Os sinais de saída são conselheiros de vida.','Exit signs are life coaches.'],
['Uma escova de dentes devia ter um nome de super-herói.','A toothbrush should have a superhero name.'],
['O melhor pedido de casamento é uma proposta de dividir sobremesa.','The best marriage proposal is an offer to split dessert.'],
['Uma torrada caída está só a tentar mudar de perspetiva.','Fallen toast is just trying to change perspective.'],
['Os patos ao luar são a melhor terapia de casal.','Moonlit ducks are the best couples therapy.'],
['A felicidade eterna cabe no cesto de uma bicicleta.','Everlasting happiness fits in a bicycle basket.'],
['Esta app devia ganhar o Nobel da Conversa Fiada.','This app deserves the Nobel Prize for Small Talk.']
];
const moreQuestions=[
['A vossa primeira empresa falida vende…','Your first failed business sells…','🫧','Ar de discoteca em frasco','Bottled nightclub air','🦆','Seguros para patos','Duck insurance','🧦','Meias por assinatura emocional','Emotional sock subscriptions'],
['A tua campanha para presidente da pista promete…','Your dance-floor presidential campaign promises…','🪩','Techno a meio gás','Half-speed techno','🧃','Sumo no bengaleiro','Cloakroom juice','🛋️','Sofás no refrão','Sofas during the chorus'],
['Um alien pede uma tradição portuguesa. Mostras…','An alien asks for a Portuguese tradition. You show…','☕','Discutir o café','Debating coffee','🚌','Correr por um autocarro parado','Chasing a stationary bus','🥐','Proteger o último pastel','Protecting the last custard tart'],
['A tua autobiografia chama-se…','Your autobiography is called…','🗺️','Era já ali','It Was Just Round the Corner','⏰','Só mais cinco minutos','Just Five More Minutes','🎧','Eu conhecia esta versão','I Knew This Version'],
['És obrigado a inventar um feriado. Celebras…','You must invent a holiday. You celebrate…','🧦','A meia reencontrada','The reunited sock','🪑','A cadeira livre','The empty chair','🔋','100% de bateria','100% battery'],
['O teu pato chega atrasado ao date. A desculpa?','Your duck is late for the date. Its excuse?','🌊','Trânsito na lagoa','Pond traffic','🍞','Reunião com uma baguete','Meeting with a baguette','🦆','Confundiu os patos','Got its ducks mixed up'],
['Se esta noite fosse um eletrodoméstico…','If tonight were an appliance…','🌀','Centrifugação sem tampa','Spin cycle with no lid','🍞','Torradeira filosófica','Philosophical toaster','❄️','Frigorífico sociável','Sociable fridge'],
['Levas um prémio por…','You win an award for…','🕺','Dançar sem instruções','Dancing without instructions','🫡','Cumprimentar desconhecidos errados','Greeting the wrong strangers','🧊','Salvar um cubo de gelo','Rescuing an ice cube'],
['A tua mansão imaginária tem…','Your imaginary mansion has…','🦆','Piscina exclusiva para patos','A duck-only pool','🛗','Elevador horizontal','A horizontal lift','🥔','Museu da batata','A potato museum'],
['O pior nome para um perfume romântico?','The worst romantic perfume name?','🚌','Último Autocarro','Last Bus','🧅','Cebola Selvagem','Wild Onion','📋','Comprovativo de Morada','Proof of Address'],
['Uma lei absurda para o primeiro date…','One absurd first-date law…','🎤','Apresentações cantadas','Sung introductions','🧀','Queijo obrigatório','Mandatory cheese','🧭','Mapa do tesouro','A treasure map'],
['O teu animal de apoio à dança seria…','Your dance-support animal would be…','🦩','Flamingo contabilista','Accountant flamingo','🐙','Polvo tímido','Shy octopus','🦥','Preguiça a 140 BPM','A sloth at 140 BPM'],
['O teu futuro eu envia uma mensagem…','Your future self sends a message…','🔑','As chaves estão no bolso','The keys are in your pocket','🌮','Come qualquer coisa','Eat something','🚲','Não confies na bicicleta','Do not trust the bicycle'],
['Uma desculpa para sair de uma reunião…','An excuse to leave a meeting…','🦆','O meu pato faz anos','It is my duck’s birthday','🌕','Tenho consulta com a lua','I have an appointment with the moon','🧦','A meia ligou','My sock called'],
['A banda sonora do vosso casamento fictício…','Your fictional wedding soundtrack…','📞','Música de espera','Hold music','🫖','Chaleira em dó maior','Kettle in C major','🔔','Campainha de bicicleta','A bicycle bell']
];
questions.push(...moreQuestions.map(x=>({q:x.slice(0,2),a:[x.slice(2,5),x.slice(5,8),x.slice(8,11)]})));
challenges.push(
['És uma torradeira a receber um Óscar.','You are a toaster accepting an Oscar.'],['Mima um pato a tentar estacionar uma bicicleta.','Mime a duck trying to park a bicycle.'],['Faz o anúncio de um perfume que cheira a fila.','Advertise a perfume that smells like a queue.'],['Explica a internet a uma sardinha, só com gestos.','Explain the internet to a sardine using only gestures.'],['És um GPS que se apaixonou pela rotunda.','You are a GPS that fell in love with a roundabout.'],['Desfila como um guarda-chuva com sucesso internacional.','Strut like an internationally successful umbrella.'],['Faz uma conferência de imprensa sobre uma meia perdida.','Hold a press conference about a missing sock.'],['És um pinguim a pedir férias ao Polo Sul.','You are a penguin requesting leave from the South Pole.'],['Faz o boletim de trânsito para uma lagoa de patos.','Give a traffic report for a duck pond.'],['Mima uma máquina de café com síndrome de estrela.','Mime a coffee machine with celebrity attitude.'],['És um caracol a ganhar os cem metros.','You are a snail winning the hundred metres.'],['Apresenta o teu joelho como candidato presidencial.','Introduce your knee as a presidential candidate.'],['Dança um refrão que só tu consegues ouvir.','Dance to a chorus only you can hear.'],['Faz de maestro de uma orquestra de micro-ondas.','Conduct an orchestra of microwaves.'],['És uma gaivota a negociar o preço de uma batata.','You are a seagull negotiating the price of a chip.'],['Mima um segurança a revistar uma nuvem.','Mime a bouncer searching a cloud.'],['Faz uma previsão astrológica para uma bicicleta.','Give a bicycle an astrological forecast.'],['És uma planta a reclamar do vaso.','You are a plant complaining about its pot.'],['Faz uma chamada para o apoio técnico da lua.','Call the moon’s technical support.'],['Ensina um passo de dança a um extraterrestre imaginário.','Teach a dance move to an imaginary alien.'],['És um copo vazio a pedir um aumento.','You are an empty glass asking for a pay rise.'],['Mima um elevador a ensaiar uma entrada dramática.','Mime a lift rehearsing a dramatic entrance.'],['Dá um discurso de despedida ao último guardanapo.','Give a farewell speech to the last napkin.'],['Faz o trailer de um filme chamado A Vingança do Bengaleiro.','Perform the trailer for Revenge of the Cloakroom.']);
pitches.push(...convincePrompts.map(p=>['Convence-nos: '+p[0],'Convince us: '+p[1]]));
const romanceQuestions=[
 {q:['O primeiro encontro perfeito inclui…','The perfect first date includes…'],a:[['🦆','Ver patos ao luar','Watching moonlit ducks'],['🛒','Comparar preços de cereais','Comparing cereal prices'],['🚲','Perdermo-nos de bicicleta','Getting lost on a bicycle']]},
 {q:['A vossa casa de sonho tem…','Your dream home has…'],a:[['🦆','Uma lagoa para patos','A duck pond'],['🪩','Bola de espelhos na cozinha','A kitchen disco ball'],['🛋️','Sofá com serviço de snacks','A sofa with snack service']]},
 {q:['Uma prova absurda de amor seria…','An absurd proof of love would be…'],a:[['🥔','Guardar a última batata frita','Saving the last chip'],['🔌','Trazer o carregador certo','Bringing the right charger'],['🦆','Aprender a falar pato','Learning to speak duck']]},
 {q:['O vosso plano romântico de domingo…','Your romantic Sunday plan…'],a:[['🦆','Dar nomes aos patos','Naming the ducks'],['📚','Julgar títulos de livros','Judging book titles'],['🥐','Uma expedição pelo melhor pastel','An expedition for the best custard tart']]},
 {q:['A vossa discussão de casal fictícia seria sobre…','Your fictional couple argument would be about…'],a:[['🍕','Ananás e soberania da pizza','Pineapple and pizza sovereignty'],['🦆','Quem ficou com o pato','Who got the duck'],['🎧','Quem estragou a playlist','Who ruined the playlist']]},
 {q:['O vosso hino romântico?','Your romantic anthem?'],a:[['🫖','Um dueto de chaleiras','A kettle duet'],['🦆','Um pato em dó maior','A duck in C major'],['📞','Música de espera em remix','Remixed hold music']]},
 {q:['Lua de mel imaginária?','Imaginary honeymoon?'],a:[['🌕','Na lua, obviamente','On the moon, obviously'],['🛒','Na secção de congelados','In the frozen food aisle'],['🦆','Num retiro de patos','At a duck retreat']]},
 {q:['O vosso ritual de boa noite seria…','Your goodnight ritual would be…'],a:[['📋','Ata da reunião do dia','Minutes of the day’s meeting'],['🎭','Um elogio em francês inventado','A compliment in made-up French'],['🦆','Um quá de respeito','A respectful quack']]},
 {q:['Qual seria o vosso negócio em casal?','What would your couple business be?'],a:[['🦆','Consultoria sentimental para patos','Duck relationship consultancy'],['🧦','Reunião de meias perdidas','Reuniting lost socks'],['🚲','Bicicletas com terapia incluída','Bicycles with therapy included']]},
 {q:['O símbolo do vosso amor fictício?','The symbol of your fictional love?'],a:[['🔋','Uma powerbank carregada','A charged power bank'],['🦆','Dois patos sincronizados','Two synchronised ducks'],['🥔','Uma batata em forma de coração','A heart-shaped potato']]}
];
const grillBank=[
['Que date esta pessoa escolheria?','Which date would this person choose?',['Um passeio sem plano','A walk with no plan'],['Jantar com reserva','Dinner with a booking'],['Um jogo absurdo','An absurd game'],['Qual seria o primeiro desvio?','What would be the first detour?'],['O que pedirias para partilhar?','What would you order to share?'],['Que regra inventavas?','What rule would you invent?']],
['Como é que esta pessoa mostra que gosta de alguém?','How does this person show they like someone?',['Faz rir','Makes them laugh'],['Lembra-se dos detalhes','Remembers small details'],['Aparece quando importa','Shows up when it matters'],['Qual foi a piada que te conquistou?','What joke won you over?'],['Que detalhe gostas que notem?','What detail do you like people to notice?'],['Que gesto pequeno conta muito?','What small gesture means a lot?']],
['O que salva um date estranho para esta pessoa?','What saves an awkward date for this person?',['Assumir o embaraço','Admitting the awkwardness'],['Mudar de sítio','Changing venue'],['Pedir sobremesa','Ordering dessert'],['Que frase usarias para quebrar o gelo?','What would you say to break the ice?'],['Para onde fugíamos, sem pressa?','Where would we wander, with no rush?'],['Qual sobremesa teria essa responsabilidade?','Which dessert could handle that responsibility?']],
['Como seria um domingo feliz desta pessoa?','What is this person’s happy Sunday?',['Rua e aventura','Outdoors and adventure'],['Sofá e silêncio','Sofa and silence'],['Amigos e comida','Friends and food'],['Qual o próximo sítio que queres descobrir?','Where do you want to discover next?'],['O que torna o silêncio confortável?','What makes silence comfortable?'],['Qual é a tua receita de juntar pessoas?','What is your recipe for bringing people together?']],
['O que esta pessoa valoriza numa conversa?','What does this person value in a conversation?',['Perguntas inesperadas','Unexpected questions'],['Saber ouvir','Listening well'],['Humor sem esforço','Effortless humour'],['Que pergunta nunca te fazem?','What question does nobody ask you?'],['Como notas que te estão a ouvir?','How can you tell someone is listening?'],['O que te faz rir sem falhar?','What always makes you laugh?']],
['Qual seria a viagem improvisada desta pessoa?','What spontaneous trip would this person take?',['Comboio sem destino','Train with no destination'],['Uma praia vazia','An empty beach'],['Cidade com boa comida','A city with good food'],['Que música ia no caminho?','What song comes along?'],['O que levavas no saco?','What would you pack?'],['O que provaríamos primeiro?','What would we taste first?']],
['Como reage esta pessoa a um plano cancelado?','How does this person react to a cancelled plan?',['Inventa outro','Makes a new one'],['Celebra de pijama','Celebrates in pyjamas'],['Liga a um amigo','Calls a friend'],['Qual é o teu plano B favorito?','What is your favourite plan B?'],['Qual é o teu ritual de descanso?','What is your rest ritual?'],['Quem costuma salvar o dia?','Who usually saves the day?']],
['Que elogio esta pessoa preferia?','Which compliment would this person prefer?',['Tens imensa graça','You are really funny'],['Sinto-me à vontade contigo','I feel at ease with you'],['Tens boas ideias','You have good ideas'],['Qual é o teu humor secreto?','What is your secret sense of humour?'],['O que te deixa à vontade?','What puts you at ease?'],['Que ideia maluca queres realizar?','What wild idea do you want to try?']],
['Como seria a playlist de um date desta pessoa?','What would this person’s date playlist be?',['Clássicos sem vergonha','Shameless classics'],['Descobertas estranhas','Strange discoveries'],['O outro escolhe','The other person picks'],['Qual cantarias sem música?','Which would you sing without music?'],['Que artista devia eu ouvir?','What artist should I hear?'],['Que música estarias a torcer para ouvir?','What song would you secretly hope for?']],
['O que faz esta pessoa voltar a querer conversar?','What makes this person want another conversation?',['Curiosidade','Curiosity'],['Leveza','Lightness'],['Uma boa discordância','A good disagreement'],['Sobre o que nunca te cansas de aprender?','What do you never tire of learning about?'],['O que torna uma noite leve?','What makes a night feel easy?'],['Em que assunto tens uma opinião impopular?','What topic gives you an unpopular opinion?']],
['Num primeiro date, esta pessoa seria…','On a first date, this person would be…',['Pontual','On time'],['Cinco minutos atrasada','Five minutes late'],['Já no sítio errado','Already at the wrong venue'],['Como passas os cinco minutos de espera?','How do you spend five minutes waiting?'],['Qual a tua desculpa mais honesta?','What is your most honest excuse?'],['Qual foi a tua melhor desorientação?','What was your best wrong turn?']],
['A pessoa preferia receber…','This person would rather receive…',['Uma carta parva','A silly letter'],['Um passeio surpresa','A surprise walk'],['O snack certo','The right snack'],['Qual seria a primeira frase da carta?','What would the letter’s first line be?'],['Surpresa total ou uma pista?','Total surprise or one clue?'],['Qual snack ganha sempre?','Which snack always wins?']],
['Que lado desta pessoa demora a aparecer?','Which side of this person takes time to appear?',['O lado palhaço','The clown side'],['O lado sentimental','The sentimental side'],['O lado competitivo','The competitive side'],['Em que contexto aparece?','When does it appear?'],['Que pequena coisa te comove?','What small thing moves you?'],['Em que jogo perdes a compostura?','What game makes you lose composure?']],
['O que esta pessoa prefere decidir num date?','What does this person prefer to decide on a date?',['O sítio','The venue'],['A comida','The food'],['Nada, deixa fluir','Nothing, go with the flow'],['Qual sítio conta uma história tua?','What place tells your story?'],['Que prato te define mal mas diverte?','What dish describes you badly but amusingly?'],['O que faz um improviso correr bem?','What makes improvisation work?']],
['O que faria esta pessoa rir agora?','What would make this person laugh right now?',['Um trocadilho horrível','A terrible pun'],['Uma imitação de pato','A duck impression'],['Uma história embaraçosa tua','Your embarrassing story'],['Arrisca o pior trocadilho, se quiseres.','Try your worst pun, if you like.'],['Pato formal ou pato de férias?','Formal duck or holiday duck?'],['Qual história podes contar sem expor ninguém?','What story can you tell without embarrassing someone else?']],
['Como recarrega esta pessoa a bateria social?','How does this person recharge socially?',['Sozinha um bocado','Some time alone'],['Com a pessoa certa','With the right person'],['A fazer qualquer coisa','By doing something'],['Qual é o teu refúgio favorito?','What is your favourite refuge?'],['Que qualidade torna alguém fácil de estar?','What quality makes someone easy to be around?'],['Que atividade te devolve energia?','What activity gives you energy back?']],
['O que esta pessoa nunca levaria demasiado a sério?','What would this person never take too seriously?',['Horóscopos','Horoscopes'],['Jogos de tabuleiro','Board games'],['Esta app','This app'],['Qual seria o teu signo inventado?','What would your invented star sign be?'],['Que regra costumas inventar?','What rule do you tend to invent?'],['Que prémio mereciam os criadores?','What award do the creators deserve?']],
['Como é o pequeno-almoço ideal desta pessoa?','What is this person’s ideal breakfast?',['Café e pressa','Coffee and a hurry'],['Mesa cheia','A full table'],['Já é almoço','It is already lunch'],['O café é ritual ou combustível?','Is coffee ritual or fuel?'],['Qual é o item obrigatório?','What is the essential item?'],['A que horas começa o teu domingo?','What time does your Sunday start?']],
['Que talento inútil teria esta pessoa?','What useless talent would this person have?',['Reconhecer músicas em 1 segundo','Recognising songs in 1 second'],['Encontrar a saída','Finding the exit'],['Inventar desculpas poéticas','Inventing poetic excuses'],['Que música reconheces sempre?','What song do you always recognise?'],['Qual é a melhor saída para uma noite boa?','What is the best ending to a good night?'],['Inventa uma desculpa para um pato atrasado.','Invent an excuse for a late duck.']],
['O próximo encontro imaginário teria…','The next imaginary date would include…',['Um desafio novo','A new challenge'],['Uma conversa longa','A long conversation'],['Patos, obviamente','Ducks, obviously'],['O que gostavas de experimentar pela primeira vez?','What would you like to try for the first time?'],['Que assunto deixarias para essa conversa?','What topic would you save for that conversation?'],['Já temos nomes para os patos?','Do we have names for the ducks yet?']]
];
const bags=new Map();
function drawIds(key,length,count){let bag=bags.get(key)||[];const result=[];while(result.length<count){if(!bag.length){bag=Array.from({length},(_,i)=>i);for(let i=bag.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[bag[i],bag[j]]=[bag[j],bag[i]]}}const index=bag.findIndex(id=>!result.includes(id));if(index<0){bag=[];continue}result.push(bag.splice(index,1)[0]);}bags.set(key,bag);return result;}
