// Tap-only Grill: one opening question and four binary follow-ups per person.
const grillIcons=[['🚶','🍽️'],['😄','📝'],['😅','🧭'],['🌿','🛋️'],['❓','👂'],['🚂','🏖️'],['🧭','🛋️'],['😄','🤝'],['🎵','🎧'],['🔎','☁️'],['⏰','⌛'],['💌','🗺️'],['🤡','💛'],['📍','🍽️'],['💬','🦆'],['🌙','🤝'],['🔮','🎲'],['☕','🥐'],['🎧','🚪'],['✨','💬']];
const binaryBranches=[
 [['Prefere inventar o plano na hora?','Would they rather invent the plan on the spot?'],['Sim, improviso total','Yes, total improvisation'],['Não, um plano secreto','No, a secret plan']],
 [['Se o plano falhar, mantém a pose?','If the plan fails, do they keep a straight face?'],['Ri-se logo','Laughs immediately'],['Culpa o GPS','Blames the GPS']],
 [['Leva um snack de emergência?','Do they bring an emergency snack?'],['Claro, prioridades','Of course, priorities'],['Não, vive do suspense','No, lives on suspense']],
 [['Aceita um pato como conselheiro amoroso?','Would they accept a duck as a love adviser?'],['Só se tiver referências','Only with references'],['O pato já está contratado','The duck is already hired']],
 [['Escolheria uma surpresa ou uma pista?','Would they choose a surprise or a clue?'],['Surpresa completa','Complete surprise'],['Uma pista, por favor','One clue, please']],
 [['Se a música mudar, muda o plano?','If the music changes, do they change the plan?'],['Segue o ritmo','Follows the rhythm'],['Defende a playlist','Defends the playlist']],
 [['A última batata frita seria…','The last chip would be…'],['Para partilhar','For sharing'],['Tema de negociação','A negotiation topic']],
 [['O final perfeito tem uma bicicleta?','Does the perfect ending involve a bicycle?'],['Sim, com um pato no cesto','Yes, with a duck in the basket'],['Só se o GPS não julgar','Only if the GPS does not judge']]
];
function grillIntroView(){return `${back()}${modeArt('grill')}${eyebrow('Grill me · só dois botões','Grill me · just two buttons')}${heading('Lê a pessoa.<br>Toca numa hipótese.','Read the person.<br>Tap a hunch.')}<p class="sub">${t('Duas pessoas, à vez. Uma pergunta sobre a outra pessoa, depois quatro seguimentos com duas opções. Nada para explicar. Nada para dizer em voz alta.','Two people, taking turns. One question about the other person, then four follow-ups with two choices. Nothing to explain. Nothing to say aloud.')}</p><div class="binary-preview"><span>①<br>${t('Isto','This')}</span><b>OU / OR</b><span>②<br>${t('Aquilo','That')}</span></div><div class="stack">${btn('Bora · só toques','Let’s go · taps only','grill-begin')}${btn('Prefiro outro jogo','I’d prefer another game','modes','','secondary')}</div><p class="privacy">${t('É um palpite divertido, não uma leitura psicológica. Podes passar em qualquer momento.','A playful guess, not a psychological reading. Pass whenever you like.')}</p>`}
function grillBegin(){grill={index:0,step:0,ids:drawIds('grill',grillBank.length,2),paths:[[],[]],skipped:0,results:[]};go('grill-guess')}
function grillCurrent(){const root=grillBank[grill.ids[grill.index]],path=grill.paths[grill.index];if(grill.step===0)return {q:root.slice(0,2),options:root.slice(2,4),icons:grillIcons[grill.ids[grill.index]],caption:t('Primeira impressão','First impression')};const previous=path[path.length-1],branch=binaryBranches[(grill.step-1)*2+previous];return {q:branch[0],options:branch.slice(1),icons:[['🧭','🗺️'],['🎵','🎧'],['🍟','🤝'],['🦆','🚲']][grill.step-1],caption:t('Seguimento '+grill.step+' / 4 · o teu palpite anterior conta','Follow-up '+grill.step+' / 4 · your previous hunch shapes this')};}
function grillView(){const current=grillCurrent(),target=1-grill.index;return `${back()}${eyebrow('Dossier '+(grill.index+1)+' / 2','Dossier '+(grill.index+1)+' / 2')}<div class="turn">${name(grill.index)} → ${t('sobre','about')} ${name(target)}</div><div class="grill-steps">${Array.from({length:5},(_,i)=>`<i class="${i<=grill.step?'lit':''}"></i>`).join('')}</div><div class="caption">${current.caption}</div>${heading(...current.q)}<div class="binary-options">${current.options.map((o,i)=>`<button class="binary-option" data-action="grill-tap" data-value="${i}"><span class="binary-icon" aria-hidden="true">${current.icons[i]}</span><span>${t(...o)}</span><small>${i===0?'A':'B'} ↗</small></button>`).join('')}</div><p class="privacy">${t('Só escolher. Sem explicar. A próxima pergunta segue o teu palpite.','Just choose. No explanation. The next question follows your hunch.')}</p><div class="stack">${btn('Passar este dossier','Skip this dossier','grill-skip','','secondary small')}</div>`}
function grillTap(value){grill.paths[grill.index].push(Number(value));grill.step++;if(grill.step===5)grillAdvance();else go('grill-guess')}
function grillAdvance(skipped=false){if(skipped)grill.skipped++;grill.index++;grill.step=0;go(grill.index===2?'grill-end':'grill-handoff')}
function grillHandoff(){return `${back()}${modeArt('grill')}${heading('Agora troca<br>de detetive.','Now swap<br>detectives.')}<div class="result-card"><h2>${name(1)}</h2><p class="copy">${t('Cinco toques sobre a outra pessoa. Sem interrogatório em voz alta.','Five taps about the other person. No spoken interrogation.')}</p></div><div class="actions">${btn('A minha vez','My turn','grill-ready')}${btn('Passo esta','I’ll pass','grill-skip','','pink')}</div>`}
function grillEndView(){return `${back()}${modeArt('grill')}${heading('Investigação concluída.<br>Rigor duvidoso.','Investigation complete.<br>Questionable rigour.')}<div class="stack">${grill.paths.map((path,i)=>`<div class="dossier"><div class="caption">${name(i)} → ${name(1-i)}</div><p>${path.length===5?t(path.filter(x=>x===0).length>=3?'Detetive do improviso. Vê aventuras onde os outros veem uma fila.':'Detetive do plano B. Já reservou uma mesa para o pato.',path.filter(x=>x===0).length>=3?'Improvisation detective. Sees adventures where others see a queue.':'Plan B detective. Already booked a table for the duck.'):t('Dossier reservado. Privacidade impecável.','Sealed dossier. Excellent privacy.')}</p><small>${path.length}/5 ${t('escolhas · nenhum diagnóstico real','choices · no real diagnosis')}</small></div>`).join('')}</div><p class="privacy">${t('Nenhuma resposta tinha de ser justificada. Nenhuma destas teorias é ciência.','No answer needed a justification. None of these theories are science.')}</p><div class="stack">${btn('Outro dossier','Another dossier','grill-begin')}${btn('Prémio para os detetives 🚲','A prize for the detectives 🚲','social-prize','','secondary')}${btn('Outro modo','Another mode','modes','','secondary')}</div>`}
let glitchClicks=0,glitchNext=7,glitchOpen=false;
function showGlitch(){if(glitchOpen)return;glitchOpen=true;const host=document.createElement('div');host.id='glitch-layer';host.className='glitch-layer';host.innerHTML=`<div class="glitch-card" role="dialog" aria-modal="true" aria-labelledby="glitch-title"><div class="caption">ERROR 404 · ${t('competência não encontrada','competence not found')}</div><div class="glitch-face" aria-hidden="true">×_×</div><h2 id="glitch-title">${t('App bloqueada.','App blocked.')}</h2><p>${t('Os dois patetas que a fizeram não percebem nada disto.','The two idiots who made it have no idea what they are doing.')}</p><small>${t('É só uma piada. O jogo está exatamente onde o deixaste.','Just a joke. Your game is exactly where you left it.')}</small><button class="btn" data-action="glitch-close">${t('Desbloquear os patetas ↗','Unblock the idiots ↗')}</button></div>`;document.body.append(host);document.querySelector('.shell').inert=true;host.querySelector('button').focus();}
function closeGlitch(){document.querySelector('#glitch-layer')?.remove();document.querySelector('.shell').inert=false;glitchOpen=false;document.querySelector('#app button')?.focus({preventScroll:true})}
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action==='glitch-close'){closeGlitch();return}if(['grill-tap','quiz-answer','answer','convince-rate'].includes(action)){glitchClicks++;if(glitchClicks>=glitchNext&&!running&&!wheel.spinning){glitchNext=glitchClicks+10+Math.floor(Math.random()*9);showGlitch()}}});
document.addEventListener('keydown',e=>{if(glitchOpen&&(e.key==='Escape'||e.key==='Enter')){e.preventDefault();closeGlitch()}if(glitchOpen&&e.key==='Tab'){e.preventDefault();document.querySelector('#glitch-layer button')?.focus()}});
