let activeMode='home',convince=null,grill=null,romanceCount=2;
function homeV2(){return `${eyebrow('Experiência social de qualidade duvidosa','A social experiment of questionable quality')}<div class="intro"><h1 tabindex="-1">${t('ISTO DÁ<br><span class="accent">ENGATE?</span>','DOES THIS<br><span class="accent">FLIRT WORK?</span>')}</h1><div class="hero-bottom"><p class="lead">${t('Dois gajos fizeram uma app para meter conversa e descobrir se isto dá engate.<br><br>Tu decides se tem piada.','Two guys made an app to start conversations and see if flirting comes out of it.<br><br>You decide if it’s any good.')}</p><div class="sticker">${t('TU<br>DECIDES','YOUR<br>CALL')}<small>★ ZERO ${t('PRESSÃO','PRESSURE')} ★</small></div></div></div><div class="mascots"><span class="orbit">${t('OS CULPADOS','THE CULPRITS')}<br>↓ ↓</span>${mascots}</div><div class="actions">${btn('Bora testar ↗','Let’s test ↗','test')}${btn('Não, obrigada','No, thanks','no','','pink')}</div><p class="sub" style="font-size:14px;text-align:center">${t('Se der conversa, ótimo. Se não der, os dois gajos sobrevivem.','If it starts a conversation, great. If not, the two guys will survive.')}</p>${privacy()}`}
function modeArt(mode){const drawings={
 game:'<path d="M24 72h45l23-36 29 36H69l34-35 30 35M92 36h16M123 21h17l25 51"/><circle cx="45" cy="72" r="27"/><circle cx="165" cy="72" r="27"/>',
 love:'<path d="M100 92C35 58 44 12 72 20q20 3 28 20 8-17 28-20c28-8 37 38-28 72Z"/><path d="M45 94l110-80M43 86l2 8 10 1M147 14h8v9"/>',
 convince:'<path d="M40 20h126v60H92L64 101V80H40Z"/><path d="M60 40h78M60 57h53"/><path d="M15 32l14 6M177 26l16-8M179 68l15 8"/>',
 grill:'<circle cx="94" cy="45" r="29"/><path d="M114 67l37 35M75 40q0-15 18-15t14 18l-12 8M94 63v2M32 22h18M32 38h18M32 54h18"/>'};return `<div class="mode-art ${mode}" aria-hidden="true"><svg viewBox="0 0 210 112" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round" stroke-linejoin="round">${drawings[mode]}</svg><span>${{game:'01 / PLAY',love:'02 / LOVE LAB',convince:'03 / HOT TAKES',grill:'04 / GRILL ME'}[mode]}</span></div>`}
function modeCard(mode,num,pt,en,subpt,suben,action){return `<button class="mode-card ${mode}" data-action="${action}"><span class="mode-number">${num}</span><span><strong>${t(pt,en)}</strong><small>${t(subpt,suben)}</small></span><span class="mode-symbol" aria-hidden="true">${{game:'✳',love:'♡',convince:'↗',grill:'◎'}[mode]}</span></button>`}
function modesView(){return `${back()}${eyebrow('Escolhe o teu disparate','Choose your nonsense')}${heading('Quatro maneiras<br>de meter conversa.','Four ways<br>to break the ice.')}<p class="sub">${t('Sem currículo amoroso. Sem obrigações. Só boa conversa, se vos apetecer.','No dating CV. No obligations. Just good conversation, if you feel like it.')}</p><div class="mode-menu">${modeCard('game','01','Jogo da bicicleta','The bicycle game','2–4 · perguntas, desafios e votação','2–4 · questions, challenges and voting','setup')}${modeCard('love','02','Amor de laboratório','Laboratory love','2–4 · avatares + matches disparatados','2–4 · avatars + ridiculous matches','quiz-start')}${modeCard('convince','03','Tenta convencer-me','Try to convince me','100 prompts · 10 por partida','100 prompts · 10 per game','convince-start')}${modeCard('grill','04','Grill me para dating','Grill me for dating','2 · adivinha, confirma, pergunta mais','2 · guess, confirm, ask a little more','grill-start')}</div><div class="stack">${btn('Ou chumbar os dois criadores','Or reject both creators','tester','','secondary small')}</div>${privacy()}`}
function setMode(mode){activeMode=mode;}
function applyMode(){document.body.dataset.mode=activeMode;}
function romanceSetupView(){return `${back()}${modeArt('love')}${eyebrow('Amor de laboratório','Laboratory love')}${heading('O Cupido tirou<br>um curso online.','Cupid took<br>an online course.')}<p class="sub">${t('Cada pessoa responde a cinco perguntas. No fim: avatares, matches e previsões amorosas cientificamente parvas.','Each person answers five questions. Then: avatars, matches and scientifically silly romantic forecasts.')}</p><div class="selection">${[2,3,4].map(n=>`<button class="chip ${romanceCount===n?'active':''}" data-action="romance-count" data-value="${n}">${n} ${t('pessoas','people')}</button>`).join('')}</div>${btn('Entrar no laboratório ♡','Enter the laboratory ♡','romance-begin')}<p class="privacy">${t('Ciência 100% inventada. Um match não implica interesse nem compromisso.','100% made-up science. A match implies neither interest nor commitment.')}</p>`}
function startRomance(){quiz={turn:0,q:0,count:romanceCount,answers:Array.from({length:romanceCount},()=>[]),questions:[...quizQuestions,...drawIds('romance',romanceQuestions.length,2).map(i=>romanceQuestions[i])]};go('quiz-handoff')}
function pairMatch(i,j){let shared=[];quiz.answers[i].forEach((v,q)=>{if(v===quiz.answers[j][q])shared.push(q)});const match=shared.length>=3;let story;
 const duckQ=shared.find(q=>quiz.questions[q].a[quiz.answers[i][q]][0]==='🦆');
 if(match&&duckQ!==undefined)story=t('Gostam dos mesmos patos. Vão vê-los ao luar e ser felizes para sempre. Até acabar o pão.','You like the same ducks. You will watch them by moonlight and live happily ever after. Until the bread runs out.');
 else if(match){const q=shared[shared.length-1],answer=quiz.questions[q].a[quiz.answers[i][q]];story=t('Unidos por «'+answer[1]+'». O casamento será numa rotunda. A bicicleta leva as alianças.','United by “'+answer[2]+'”. The wedding is at a roundabout. The bicycle carries the rings.');}
 else if(!shared.length)story=t('Um quer patos ao luar. O outro quer a senha do Wi-Fi. O Cupido pediu transferência.','One wants moonlit ducks. The other wants the Wi-Fi password. Cupid requested a transfer.');
 else story=t('Partilham '+shared.length+' disparates, mas discutiriam a custódia de uma torradeira. Amizade diplomática aprovada.','You share '+shared.length+' silly ideas, but would argue over toaster custody. Diplomatic friendship approved.');
 return {i,j,shared,match,story,percent:shared.length*20};}
function romanceView(){if(screen==='quiz-handoff')return `${back()}${modeArt('love')}${eyebrow('Experiência '+(quiz.turn+1)+' / '+quiz.count,'Experiment '+(quiz.turn+1)+' / '+quiz.count)}${heading('Chamamos a próxima cobaia.','Our next volunteer, please.')}<div class="result-card"><h2>${name(quiz.turn)}</h2><p class="copy">${t('Cinco perguntas. Os outros não espreitam: o Cupido é muito rigoroso.','Five questions. No peeking: Cupid takes this very seriously.')}</p></div><div class="actions">${btn('Aceito ♡','I’m in ♡','quiz-ready')}${btn('Passo, obrigada','I’ll pass, thanks','leave','','pink')}</div><p class="privacy">${t('Método inventado. Participação opcional.','Invented method. Optional participation.')}</p>`;
 if(screen==='quiz'){const q=quiz.questions[quiz.q];return `${back()}${eyebrow('Estudo amoroso · '+(quiz.q+1)+' / 5','Romance study · '+(quiz.q+1)+' / 5')}<div class="turn">${name(quiz.turn)}</div>${heading(...q.q)}<div class="options">${q.a.map((a,i)=>opt(...a,'quiz-answer',i)).join('')}</div><p class="tagline">${t('A resposta mais honesta também pode ser a mais parva.','The most honest answer can also be the silliest.')}</p>`}
 const pairs=[];for(let i=0;i<quiz.count;i++)for(let j=i+1;j<quiz.count;j++)pairs.push(pairMatch(i,j));
 return `${back()}${modeArt('love')}${eyebrow('Instituto de Romance Altamente Duvidoso','Institute of Highly Questionable Romance')}${heading('Os resultados<br>são gravíssimos.','The results<br>are very serious.')}<p class="sub">${t('Método: cinco respostas, dois tubos de ensaio e uma opinião de um pato.','Method: five answers, two test tubes and a duck’s opinion.')}</p><div class="avatar-grid">${quiz.answers.map((a,i)=>`<div class="avatar-card"><div class="caption">${name(i)}</div>${quizAvatar(a,i)}<strong>${t(quizQuestions[0].a[a[0]][1],quizQuestions[0].a[a[0]][2])}</strong><small>${t(quizQuestions[1].a[a[1]][1],quizQuestions[1].a[a[1]][2])}<br>${t(quizQuestions[2].a[a[2]][1],quizQuestions[2].a[a[2]][2])}</small></div>`).join('')}</div><div class="stack">${pairs.map(p=>`<article class="match-card"><div class="caption">${name(p.i)} + ${name(p.j)}</div><div class="match-title">${p.match?'♡ MATCH':t('↗ NÃO DEU MATCH','↗ NO MATCH')}</div><div class="huge">${p.percent}%</div><p class="copy">${p.story}</p><p class="tagline">${p.shared.length}/5 ${t('respostas iguais · romance fictício','matching answers · fictional romance')}</p></article>`).join('')}</div><p class="privacy">${t('Paródia científica. Não mede atração nem prevê relações. Vocês decidem se querem continuar a conversa.','Scientific parody. It measures neither attraction nor relationship prospects. You decide whether to continue chatting.')}</p><div class="stack">${btn('Receber a bicicleta 🚲','Get the bicycle 🚲','quiz-prize')}${btn('Outra experiência ♡','Another experiment ♡','romance-begin','','secondary')}${btn('Escolher outro modo','Choose another mode','modes','','secondary')}</div>`}
function convinceSetupView(){return `${back()}${modeArt('convince')}${eyebrow('Tenta convencer-me de…','Try to convince me that…')}${heading('Argumentos fracos.<br>Convicção forte.','Weak arguments.<br>Strong conviction.')}<p class="sub">${t('100 ideias absurdas. Dez por partida, sem repetir. Falem à vez; quem ouve decide se ficou convencido.','100 absurd ideas. Ten per game, no repeats. Take turns speaking; the listeners decide whether they are convinced.')}</p><div class="selection">${[2,3,4].map(n=>`<button class="chip ${convince.count===n?'active':''}" data-action="convince-count" data-value="${n}">${n} ${t('pessoas','people')}</button>`).join('')}</div>${btn('Dá-me 10 disparates ↗','Give me 10 absurd ideas ↗','convince-begin')}<p class="privacy">${t('Dez segundos sugeridos, sem obrigação. Passar é grátis. Os devs podem fazer por ti.','Ten seconds suggested, no obligation. Passing is free. The devs can step in for you.')}</p>`}
function convinceBegin(){convince={count:convince.count,index:0,ids:drawIds('convince',100,10),results:[],delegated:false};remaining=10;go('convince')}
function convinceView(){const p=convincePrompts[convince.ids[convince.index]],who=convince.index%convince.count;
 return `${back()}${modeArt('convince')}${eyebrow('Disparate '+(convince.index+1)+' / 10','Absurd idea '+(convince.index+1)+' / 10')}<div class="turn">${name(who)} · ${t('tenta convencer-nos','try to convince us')}</div><h2 tabindex="-1" class="pitch-prompt">${t(p[0],p[1])}</h2><p class="sub">${t('Um argumento. Uma frase brilhante. Ou uma péssima imitação de advogado.','One argument. One brilliant sentence. Or a terrible lawyer impression.')}</p>${convince.delegated?`<div class="turn">${t('Os devs argumentam por ti. Tu relaxas.','The devs argue for you. You relax.')}</div>`:''}<div class="speech-clock"><span id="timer" role="timer">${remaining}</span><span>${t('segundos sugeridos','suggested seconds')}</span></div>${!running&&remaining>0?btn('Ligar cronómetro opcional','Start optional timer','convince-timer','','secondary small'):''}<p class="caption spaced">${t('Quem ouve decide, sem pressão:','Listeners decide, no pressure:')}</p><div class="actions">${btn('Convenceu-me','Convinced me','convince-rate','yes')}${btn('Não compramos','Not buying it','convince-rate','no','pink')}</div><div class="stack">${btn('Os devs fazem por mim','The devs do it for me','convince-delegate','','secondary small')}${btn('Passar esta','Pass this one','convince-rate','skip','secondary small')}</div>`}
function convinceReaction(){const result=convince.results[convince.index];return `${back()}${modeArt('convince')}${eyebrow('Veredicto do público','Audience verdict')}${heading(result==='yes'?'Comprámos a ideia.':result==='skip'?'Essa não merecia defesa.':'Objeção aceite.',result==='yes'?'We bought the idea.':result==='skip'?'Not worth defending.':'Objection accepted.')}<div class="result-card"><p class="copy">${result==='yes'?t('O Nobel da Conversa Fiada está mais perto.','The Nobel Prize for Small Talk is getting closer.'):result==='skip'?t('Bom critério. Há mais disparates na fila.','Good judgement. More nonsense is waiting.'):t('A ideia perdeu. A pessoa continua impecável.','The idea lost. The person is still excellent.')}</p></div>${btn(convince.index===9?'Ver relatório final':'Próximo disparate ↗',convince.index===9?'See final report':'Next absurd idea ↗','convince-next')}`}
function convinceEndView(){const won=convince.results.filter(x=>x==='yes').length;return `${back()}${modeArt('convince')}${heading('Dez disparates.<br>Zero processos.','Ten absurd ideas.<br>Zero lawsuits.')}<div class="result-card"><div class="huge">${won}/10</div><p class="copy">${t('ideias compradas. O departamento de bom senso pediu demissão.','ideas bought. The common-sense department has resigned.')}</p></div><div class="stack">${btn('Prémio para a bancada 🚲','A prize for the whole panel 🚲','social-prize')}${btn('Mais 10, todos diferentes','10 more, all different','convince-begin','','secondary')}${btn('Outro modo','Another mode','modes','','secondary')}</div>`}
function grillIntroView(){return `${back()}${modeArt('grill')}${eyebrow('Grill me para dating','Grill me for dating')}${heading('Menos currículo.<br>Mais curiosidade.','Less résumé.<br>More curiosity.')}<p class="sub">${t('Duas pessoas. Adivinhas uma preferência da outra. Ela confirma ou corrige. Depois vem uma pergunta de seguimento — baseada no que respondeu.','Two people. Guess a preference of the other person. They confirm or correct it. Then comes a follow-up based on their answer.')}</p><div class="dossier"><span>01 → 02 → 03</span><p>${t('ADIVINHAR → CONFIRMAR → CONVERSAR','GUESS → CONFIRM → TALK')}</p></div><div class="stack">${btn('Seis perguntas, bora ◎','Six questions, let’s go ◎','grill-begin')}${btn('Prefiro outro jogo','I’d prefer another game','modes','','secondary')}</div><p class="privacy">${t('Uma pessoa responde sobre a outra, alternadamente. Qualquer pergunta pode ser passada, sem explicação.','Take turns answering about each other. Any question can be passed, no explanation needed.')}</p>`}
function grillBegin(){grill={index:0,ids:drawIds('grill',grillBank.length,6),guess:null,actual:null,results:[],skipped:0};go('grill-guess')}
function grillView(){const q=grillBank[grill.ids[grill.index]],asker=grill.index%2,target=1-asker;let header=`${back()}${eyebrow('Grill '+(grill.index+1)+' / 6','Grill '+(grill.index+1)+' / 6')}`;
 if(screen==='grill-guess')return `${header}${modeArt('grill')}<div class="turn">${name(asker)} → ${t('sobre','about')} ${name(target)}</div>${heading(q[0],q[1])}<p class="sub">${t('Adivinha sem consultar. É uma hipótese, não um diagnóstico.','Guess without asking. It is a hunch, not a diagnosis.')}</p><div class="options">${q.slice(2,5).map((a,i)=>opt(['①','②','③'][i],...a,'grill-guess',i)).join('')}</div>${btn('Passar a pergunta','Pass the question','grill-skip','','secondary small')}`;
 if(screen==='grill-confirm')return `${header}<div class="turn">${name(target)} · ${t('agora confirma tu','now you confirm')}</div>${heading('Acertou em ti?','Did they get you right?')}<div class="dossier"><div class="caption">${t('Palpite da outra pessoa','The other person’s guess')}</div><p>${t(...q[2+grill.guess])}</p></div><p class="sub">${t('Qual é a tua resposta? Vale corrigir, sem justificar.','What is your answer? You can correct it, no explanation needed.')}</p><div class="options">${q.slice(2,5).map((a,i)=>opt(['①','②','③'][i],...a,'grill-confirm',i)).join('')}</div>${btn('Prefiro não responder','I’d rather not answer','grill-skip','','secondary small')}`;
 return `${header}${modeArt('grill')}${heading(grill.guess===grill.actual?'Boa leitura. Agora aprofunda.':'Boa surpresa. Agora pergunta.',grill.guess===grill.actual?'Good read. Now go deeper.':'Good surprise. Now ask.')}<div class="dossier"><div class="caption">${t('A resposta real','The real answer')}</div><p>${t(...q[2+grill.actual])}</p></div><div class="result-card"><div class="caption">${name(asker)} → ${name(target)}</div><p class="copy">${t(...q[5+grill.actual])}</p></div><p class="privacy">${t('Respondam em voz alta, se vos apetecer. A app fica calada.','Answer aloud, if you feel like it. The app stays quiet.')}</p><div class="stack">${btn('Já conversámos · próxima','We’ve talked · next','grill-next')}${btn('Passar o seguimento','Skip the follow-up','grill-next','','secondary small')}</div>`}
function grillAdvance(skipped=false){if(skipped)grill.skipped++;grill.index++;grill.guess=null;grill.actual=null;go(grill.index===6?'grill-end':'grill-guess')}
function grillEndView(){const correct=grill.results.filter(Boolean).length;return `${back()}${modeArt('grill')}${heading('Já sabem mais.<br>A app sai de cena.','You know more now.<br>The app steps aside.')}<div class="result-card"><div class="huge">${correct}/${grill.results.length}</div><p class="copy">${t('palpites certos. O resto são boas desculpas para perguntar mais.','correct guesses. The rest are good excuses to ask more.')}</p><p class="tagline">${grill.skipped} ${t('perguntas passadas. Respeitar isso também conta.','questions passed. Respecting that matters too.')}</p></div><div class="stack">${btn('Mais seis perguntas','Six more questions','grill-begin')}${btn('Bicicleta para a curiosidade 🚲','A bicycle for curiosity 🚲','social-prize','','secondary')}${btn('Outro modo','Another mode','modes','','secondary')}</div>`}
function extraAction(action,v){switch(action){
 case 'modes':clearClock();game=null;convince=null;grill=null;setMode('home');go('modes');return true;
 case 'quiz-start':case 'duo':setMode('love');game=null;go('romance-setup');return true;
 case 'romance-count':romanceCount=Number(v);render();return true;
 case 'romance-begin':setMode('love');startRomance();return true;
 case 'convince-start':setMode('convince');game=null;convince={count:2};go('convince-setup');return true;
 case 'convince-count':convince.count=Number(v);render();return true;
 case 'convince-begin':convinceBegin();return true;
 case 'convince-timer':startTimer();return true;
 case 'convince-delegate':convince.delegated=true;render();return true;
 case 'convince-rate':convince.results[convince.index]=v;go('convince-reaction');if(v==='yes')celebrate();return true;
 case 'convince-next':convince.index++;convince.delegated=false;remaining=10;go(convince.index===10?'convince-end':'convince');return true;
 case 'grill-start':setMode('grill');game=null;go('grill-intro');return true;
 case 'grill-begin':grillBegin();return true;
 case 'grill-guess':grill.guess=Number(v);go('grill-confirm');return true;
 case 'grill-confirm':grill.actual=Number(v);grill.results.push(grill.actual===grill.guess);go('grill-follow');return true;
 case 'grill-next':grillAdvance();return true;
 case 'grill-skip':grillAdvance(true);return true;
 case 'social-prize':game=null;prizeOwner='group';go('prize');celebrate();return true;
 }return false;}
